name: Python application

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.10"
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        conda install --yes python=3.10
        if [ -f environment.yml ]; then
          conda env update --file environment.yml --prune
        fi
    - name: Test with pytest
      run: |
        pytest