name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    steps:
    - uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: "3.10"
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        conda install --yes python=3.10
        conda env update --file environment.yml --prune
        conda init
        conda activate {{cookiecutter.project_name}}
        pip install .        
    - name: Test with pytest
      run: |
        conda activate {{cookiecutter.project_name}}
        pytest